# Generated by Django 4.1.7 on 2023-02-20 20:13

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_p', models.CharField(default='0-0-0-0-0-0', max_length=50, verbose_name='کد نوسازی')),
                ('code_erg', models.CharField(default='0', max_length=50, verbose_name='کد ارجاع')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('status', models.IntegerField(choices=[(1, 'تخریب'), (2, 'گودبرداری'), (3, 'چینش فندانسیون'), (4, 'بتن ریزی فندانسیون'), (5, 'ستون ریزی'), (6, 'تیر ریزی'), (7, 'درحال ساخت'), (8, 'زمین خالی'), (9, 'متفرقه')], verbose_name='وضعیت پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('manager', models.CharField(max_length=50, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.project', verbose_name='کد نوسازی')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(default=1010, max_length=10, verbose_name='کدملی')),
                ('l_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان عضویت')),
                ('picture', models.ImageField(help_text='لطفا یک عکس با  فامیل خود آپلود کنید', null=True, upload_to=accounts.models.employee.user_directory_path, verbose_name='تصویر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
