# Generated by Django 4.1.7 on 2023-02-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bill',
            field=models.IntegerField(default=0, verbose_name='صورتحساب'),
        ),
    ]
