# Generated by Django 4.1.7 on 2023-02-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='manager',
            new_name='project',
        ),
    ]
