# Generated by Django 4.1.7 on 2023-03-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_services_date'),
        ('accounts', '0005_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ManyToManyField(null=True, to='works.services', verbose_name='بابت '),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'تخریب'), (2, 'گودبرداری'), (3, 'چینش فندانسیون'), (4, 'بتن ریزی فندانسیون'), (5, 'ستون ریزی'), (6, 'تیر ریزی'), (7, 'درحال ساخت'), (8, 'زمین خالی'), (9, 'متفرقه')], default=9, verbose_name='وضعیت پروژه'),
        ),
    ]
