# Generated by Django 4.1.7 on 2023-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_services_date'),
        ('accounts', '0006_payment_service_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ManyToManyField(to='works.services', verbose_name='بابت '),
        ),
    ]
