# Generated by Django 4.1.7 on 2023-03-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_services_date'),
        ('accounts', '0007_alter_payment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ManyToManyField(blank=True, to='works.services', verbose_name='بابت '),
        ),
    ]
