# Generated by Django 4.1.7 on 2023-03-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_payment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='note',
            field=models.TextField(null=True, verbose_name='یادداشت ها'),
        ),
    ]
