# Generated by Django 4.1.7 on 2023-03-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_employee_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='note',
            field=models.TextField(default=' - ', null=True, verbose_name='یادداشت ها'),
        ),
    ]
