# Generated by Django 4.1.7 on 2023-02-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='manager',
        ),
    ]
