# Generated by Django 4.1.7 on 2023-03-01 21:03

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_remove_services_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست'),
        ),
    ]
