# Generated by Django 4.1.7 on 2023-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_services_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
    ]
