# Generated by Django 4.1.7 on 2023-03-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_services_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='تسویه'),
        ),
    ]
